pnpm-lock.yaml, web/package.json, web/src/layout/Head.tsx
=> set canonical URL for website pages

lib/ui-standalone/package.json
These were messing up the build in some cases.
=> fix ui-standalone build to not keep *.ts files

lib/protocol/package.json, lib/protocol/src/opencodegraph-protocol.schema.ts, lib/schema/dev/generateJsonSchemaTypes.ts, lib/schema/package.json, pnpm-lock.yaml
- Remove needless dep json-schema-ref-parser
- Use stricter options
=> clean up generateJsonSchemaTypes

lib/schema/src/opencodegraph.schema.json, lib/schema/src/opencodegraph.schema.ts, lib/ui-react/src/itemChip/ItemChip.module.css, lib/ui-react/src/itemChip/ItemChip.story.tsx, lib/ui-react/src/itemChip/ItemChip.tsx, lib/ui-standalone/src/itemChip/ItemChip.module.css, lib/ui-standalone/src/itemChip/ItemChip.story.ts, lib/ui-standalone/src/itemChip/ItemChip.ts, provider/links/index.test.ts, provider/links/index.ts, provider/prometheus/index.test.ts, provider/prometheus/index.ts, provider/storybook/index.test.ts, provider/storybook/index.ts, web/pages/playground/Preload.tsx
It was a neat demo to show an iframe when you hover a chip, but in reality it is hard to implement and make actually good:
- VS Code does not support iframes
- The user's browser may not load the iframe with their authentication, so it would only work for public resources
- Iframes introduce UI jitter because they are slow to load
- The content in iframes is hard to read
This only worked on the web (in the OpenCodeGraph integrations for [CodeMirror](https://opencodegraph.org/docs/clients/codemirror), [Sourcegraph](https://opencodegraph.org/docs/clients/sourcegraph), and [GitHub](https://opencodegraph.org/docs/clients/github)). This means that, for example, that the following chip will no longer show the iframe hover:
But images still work. For example, this chip will still show the image …
=> remove preview and previewUrl

client/monaco-editor/src/index.ts, client/vscode/src/ui/fileAnnotationsList.ts, lib/client/src/api.test.ts, lib/client/src/api.ts, lib/client/src/client/client.test.ts, lib/client/src/client/testdata/simple.js, lib/client/src/providerClient/createProviderClient.test.ts, lib/client/src/providerClient/createProviderClient.ts, lib/client/src/providerClient/testdata/provider.js, lib/client/src/providerClient/transport/createTransport.test.ts, lib/client/src/providerClient/transport/testdata/esmProvider.ts, lib/protocol/src/opencodegraph-protocol.schema.json, lib/protocol/src/opencodegraph-protocol.schema.ts, lib/schema/src/opencodegraph.schema.json, lib/schema/src/opencodegraph.schema.ts, lib/ui-react/src/itemChip/ItemChip.story.tsx, lib/ui-react/src/itemChip/ItemChip.tsx, lib/ui-standalone/src/itemChip/ItemChip.story.ts, provider/hello-world/index.test.ts, provider/hello-world/index.ts, provider/links/index.test.ts, provider/links/index.ts, provider/prometheus/index.test.ts, provider/prometheus/index.ts, provider/storybook/index.test.ts, provider/storybook/index.ts, web/content/docs/protocol.mdx
Now, providers just return `Annotation[]` from their `annotations` method. Items no longer have an `id`. It turned out to not be useful to give items an `id` because items were not often reused for multiple ranges in a file.
=> simplify AnnotationsResult

client/codemirror/src/extension.ts
This is no longer needed now that the HTML popover API is used (https://github.com/sourcegraph/opencodegraph/pull/9).
=> remove hackRootCssSelector workaround for CodeMirror

web/content/docs/community.mdx, web/content/docs/start.mdx
I think the link was accidently updated when the project was renamed. The old link here was a 404.
=> docs: link to OpenCodeGraph blog post

web/content/docs/protocol.mdx
This updates the definition in the spec to match the code.
=> docs: fix description of ItemsParams

.github/workflows/scip-typescript.yml
I cannot push a branch to the main repo directly, so I've created this PR from a fork.
=> chore: Stop uploading indexes to k8s.sgdev.org

bin/cli.mts
The CLI is great for quickly testing of a provider. This setups up the CLI to be able to do more than just `items` as a subcommand.
Note: This commit was extracted from a much larger change I have going on for testing on top of #41. I'll send out the other changes once that lands.
Ran it with my sourcegraph-search provider. See the shell session below.
<details>
```shellsession
$ cd provider/sourcegraph-search/
$ pnpm bundle
> @openctx/provider-sourcegraph-search@0.0.1 bundle /Users/keegan/src/github.com/sourcegraph/openctx/provider/sourcegraph-search
> esbuild --bundle --format=esm --outfile=dist/bundle.js index.ts
dist/bundle.js  5.4kb
⚡ Done in 2ms
$ cd ../../bin
$ cat config.json 
{
"enable": true,
"debug": true,
"providers": { …
```
=> cli: refactor support more commands

pnpm-lock.yaml, provider/sourcegraph-search/README.md, provider/sourcegraph-search/graphql.ts, provider/sourcegraph-search/index.ts, provider/sourcegraph-search/package.json, provider/sourcegraph-search/search.ts, provider/sourcegraph-search/tsconfig.json, provider/sourcegraph-search/vitest.config.ts
This is an initial Sourcegraph search provider which does unauthenticated searches against sourcegraph.com.
Test Plan: See tests done in https://github.com/sourcegraph/openctx/pull/48
=> provider: sourcegraph search provider

client/vscode/test/integration/api.test.cts, lib/client/src/providerClient/testdata/provider.js, lib/client/src/providerClient/transport/createTransport.test.ts, lib/client/src/providerClient/transport/testdata/commonjsExtProvider.cjs, lib/client/src/providerClient/transport/testdata/commonjsProvider.js, lib/client/src/providerClient/transport/testdata/emoji.js, lib/client/src/providerClient/transport/testdata/esmExtProvider.mjs, lib/client/src/providerClient/transport/testdata/esmProvider.js, lib/client/src/providerClient/transport/testdata/esmProvider.ts, lib/protocol/src/openctx-protocol.schema.json, lib/protocol/src/openctx-protocol.schema.ts, provider/google-docs/index.test.ts, provider/google-docs/index.ts, provider/hello-world/index.test.ts, provider/hello-world/index.ts, provider/links/index.test.ts, provider/links/index.ts, provider/prometheus/index.test.ts, provider/prometheus/index.ts, provider/sourcegraph-search/index.ts, provider/storybook/index.ts, provider/url-fetcher/index.ts
This PR updates the provider's protocol to implement `MetaResult` as follows. 
Before:
```
meta {
selectors?: Selector[];
meta: { name: string; }
}
```
After:
```
meta {
selectors?: Selector[];
name: string;
features?: { mentions?: boolean; }
}
```
=> Add meta.features to the providers protocol

bin/package.json, lib/protocol/src/openctx-protocol.schema.ts, package.json, pnpm-lock.yaml, provider/google-docs/package.json, provider/hello-world/package.json, provider/links/package.json, provider/prometheus/package.json, provider/sourcegraph-search/package.json, provider/storybook/package.json, provider/web/package.json, web/content/docs/creating-a-provider.mdx, web/netlify.toml, web/package.json, web/pages/playground/data.ts
- use unpkg instead of esm.sh
- standardize bundling build steps
- document how to build and publish a provider
=> improve provider build/publish steps

provider/google-docs/README.md, provider/google-docs/index.test.ts, provider/google-docs/index.ts, provider/google-docs/package.json
In the commit adding mentions we didn't update google docs to use mentions, isntead it incorrectly used the message field on ItemsParams.
This should make the provider a bit faster since we now only query the drive API at mentions time, then we hydrate the body at items time. We link between the two by extracting the document ID from the URL.
=> google docs provider uses mentions and items

client/vscode/test/integration/main.cts
The mac integration test was failing due to /tmp being actually under something that looks like
/var/folders/2f/8t5k6yr535sdw0s4glnpxrzm0000gn/T/ and vscode not being able to take links to the ipc socket that have path names longer than 103.
Test Plan: CI
=> client: use shorter tmpdir name for vscode

provider/sourcegraph-search/index.ts, provider/sourcegraph-search/search.ts
This was a bug. I do not know how to make typescript correctly assert we don't have extra fields.
=> sourcegraph-search: item should be URL field not URI

pnpm-lock.yaml, provider/notion/README.md, provider/notion/index.test.ts, provider/notion/index.ts, provider/notion/package.json, provider/notion/parse-text-from-any-block-type.d.ts, provider/notion/parse-text-from-any-block-type.js, provider/notion/tsconfig.json, provider/notion/vitest.config.ts, provider/sourcegraph-search/README.md, tsconfig.json, web/content/docs/providers/notion.mdx
This provider implements mentions and items to help find Notion pages and then turn them into content for an AI.
Note: The SDK for notion has quite tricky to use type definitions. As such I copy pasted the example JavaScript code they use and kept it as is rather than converting to TypeScript.
Test Plan: I created a notion bot integration, added a few pages then tested it manually in cody and via the integration test. The integration test was very useful during development so will keep it.
=> provider: add initial Notion provider

provider/notion/README.md, web/pages/index/+Page.tsx
The open context site does not seem to support markdown tables.
=> notion: use list for configuration options in README

provider/sourcegraph-search/index.ts
These are hangovers from the original cody implementation and are no-ops now.
=> sourcegraph-search: remove unused QUERY_PREFIXES

provider/web/index.ts
I started of removing UrlFetcherSettings type since its empty, but then realised I could also remove its use in parameters and remove the unread MetaParams.
Test Plan: ran the cli against a local version of the web bundler
```
pnpm openctx meta
pnpm openctx mentions https://cbea.ms/git-commit/
```
=> web: remove unnecessary types and params

pnpm-lock.yaml, provider/github/README.md, provider/github/client.ts, provider/github/index.ts, provider/github/package.json, provider/github/tsconfig.json, provider/github/vitest.config.ts
This PR ports the GitHub context provider from Cody to OpenCtx. 
It provides context for both PRs and Issues. 
Current Limitation:
- The user has to start a query with `issues:` or `pr:` for it to work, and no separate UI will be shown to select issues/pr. 
- The user has to mention the repo name manually as `issue:sourcegraph/openctx/1234`, as no codebase info has been passed on to OpenCtx yet.
These 2 limitations will be address in follow up PRs.
=> Implement GitHub context provider

.vscode/settings.json, doc/index.md, pnpm-lock.yaml, provider/linear/.gitignore, provider/linear/README.md, provider/linear/auth.ts, provider/linear/index.ts, provider/linear/package.json, provider/linear/tsconfig.json, provider/linear/vitest.config.ts
- Implements Linear context provider for OpenCtx, which allows to search for issues in Linear and use an issue title, description, and comments as AI content.
- Uses [@linear/sdk](https://developers.linear.app/docs/graphql/working-with-the-graphql-api#linear-sdk) to fetch issues
- Requires authorization in a Linear OAuth2 application or a personal API token
- Tested using [an OAuth2 application](https://linear.app/sourcegraph/settings/api/applications/a5c42ede-7768-45e7-bc39-e32b3208ceaf/edit) created in the Sourcegraph workspace
=> Implement Linear context provider 

client/vscode-lib/src/controller.ts, lib/client/src/client/client.ts, lib/client/src/configuration.ts, lib/client/src/providerClient/createProviderClient.ts
This PR updated the `createController`, `createClient`, `createProviderClient` to access a list of pre-imported and resolved runtime providers. 
This will allow the consumers of the OpenCtx client to pass in providers as JS objects implementing the Provider interface rather than having to bundle a provider and pass the link to the bundle file.
For now, it will be used by Cody to integrate the remote repositories search provider, which is internal to Cody.
=> Update vscode-lib openctx client to access pre-imported providers

bin/config.json, pnpm-lock.yaml, provider/slack-channel-context/README.md, provider/slack-channel-context/index.ts, provider/slack-channel-context/package.json, provider/slack-channel-context/tsconfig.json, provider/slack-channel-context/vitest.config.ts
- Implements Slack context provider for OpenCtx, which allows to search for relevant threads when mentioning a slack channel and use all the messages in the thread as the context to AI.
- Uses [@slack/web-api](https://www.npmjs.com/package/@slack/web-api) to fetch all data related to slack such as channel list, use slack search api and get thread messages etc. 
- Requires authorization using a personal User API token created via slack app.
- Tested using a personal user auth token created via slack app.
1. Add a local setup to handle the `https` redirects from slack to get the user auth token.
2. For now, we use a common user access token, with the limitation that we can only access public channels and not private channels.
https://github.com/sourcegraph/openctx/assets/20701220/15b6096f-ff …
=> Implement slack context provider

pnpm-lock.yaml, provider/linear/README.md, provider/linear/auth.ts, provider/linear/index.ts, provider/linear/package.json
- Removes `@linear/sdk` from the Linear provider to fix bundling issues and reduce the bundle size
- Published a new version with the changes in this PR
- Added the provider config to Linear for dogfooding.
Use creds from 1Password to test it locally.
=> Provider: remove `@linear/sdk` from the Linear provider

lib/client/package.json, lib/protocol/package.json, lib/protocol/src/openctx-protocol.schema.json, lib/protocol/src/openctx-protocol.schema.ts, lib/provider/package.json
- Adds an optional `description` field to mentions, to show them when available instead of URIs.
=> Protocol: add mention description

pnpm-lock.yaml, provider/devdocs/.gitattributes, provider/devdocs/README.md, provider/devdocs/__fixtures__/index.json, provider/devdocs/__fixtures__/io/index.html, provider/devdocs/__fixtures__/strconv/index.html, provider/devdocs/devdocs.ts, provider/devdocs/index.test.ts, provider/devdocs/index.ts, provider/devdocs/package.json, provider/devdocs/tsconfig.json, provider/devdocs/update-fixtures.ts, provider/devdocs/vitest.config.ts, tsconfig.json, web/content/docs/providers/devdocs.mdx, web/pages/index/+Page.tsx
This adds an initial provider which sources documentation from https://devdocs.io/
The motivation is that often you want very specific version information for a documentation set when interacting with AI, rather than what the AI was trained on. Additionally by providing exact documentation it can improve the quality of responses.
DevDocs is a great free resource of documentation in a regular format. This makes it easier for us to consume and search.
This provider will cache the index for a documentation set for 12 hours for performance reasons (and friendliness to devdocs hosting). We use fuse.js to get some scoring on results for free. I looked into using the same scorer as devdocs, but the code is not easily reusable.
Test Plan: A unit test based on real fixture data is added. …
=> provider: initial DevDocs provider

pnpm-lock.yaml, provider/linear/README.md, provider/linear/index.ts, provider/linear/package.json
- Show created/assigned items for the current user when the query is empty
- Simplify the configuration schema
- Update docs
- Uses `mention.description` instead of `mention.uri`.
Test manually
=> Provider: add initial items to the Linear provider

pnpm-lock.yaml, provider/devdocs/README.md, provider/devdocs/index.test.ts, provider/devdocs/index.ts, provider/devdocs/package.json
Now if you do not specify `urls` in your settings we will use the same defaults as DevDocs does.
Additionally the search was too fuzzy before. This lead to confusing behaviour where it looked like the integration was broken. Instead we switch to a more classic fuzzy search library.
Test Plan: tests where added to ensure fuzzy finder can find no results and that we work with the default docset. Additionally we assert that the top result on a known query.
=> provider: better search and default settings for devdocs

provider/devdocs/index.ts
From my manual testing the current logic is sufficient. However, I haven't exhaustively tested all docsets so the code is now more robust to a hash link (ie to a subsection of a page) working.
Test Plan: existing tests ensure we don't regress
=> provider: more robust content extraction for devdocs

provider/google-docs/auth.ts
My default browser is not connected to work, so being able to copy paste this URL is useful. Most CLIs that do this sort of thing will also print the URL incase the "open" call fails.
=> provider: print authorizeURL for google-docs/auth

bin/README.md, bin/cli.mts
I find it a bit annoying to include fully formed JSON as the value for OPENCTX_CONFIG. As such I make it possible to instead be a path or just directly a provider URI.
Test Plan: Tested it with different values of OPENCTX_CONFIG. Here is one example:
``` shellsession
$ OPENCTX_CONFIG=../provider/devdocs/dist/bundle.js pnpm openctx meta
[{"name":"DevDocs","mentions":{},"providerUri":"file:///home/keegan/src/github.com/sourcegraph/openctx/provider/devdocs/dist/bundle.js"}]
```
=> bin: add convenience values for OPENCTX_CONFIG

pnpm-lock.yaml, provider/linear-docs/.gitignore, provider/linear-docs/README.md, provider/linear-docs/auth.ts, provider/linear-docs/index.ts, provider/linear-docs/package.json, provider/linear-docs/tsconfig.json, provider/linear-docs/vitest.config.ts, web/content/docs/providers/linear-docs.mdx, web/pages/index/+Page.tsx
- Adds the Linear Docs provider, which is very similar to the Linear Issues provider
- Added instructions for internal testing to 1Password
1. Tested using the local `bundle.js` file.
2. Tested using the published: https://www.npmjs.com/package/@openctx/provider-linear-docs
=> Provider: add `linear-docs` provider

web/pages/docs/components/DocsLayout.tsx
Fixes https://linear.app/sourcegraph/issue/CODY-2100/docs-page-sidebarscrollbar-overlaps-main-content-in-chrome-and-safari
=> Fix sidebar nav going over content

client/vscode-lib/src/util/esmToCommonJS.test.ts, client/vscode-lib/src/util/esmToCommonJS.ts
Aliased imports, e.g. `import { foo2 as foo } from './foo.js'` are not allowed in CommonJS.
I ran into this problem because in my provider 2 different modules imported `dirname`, so in the final bundle the second import was aliased as `dirname2`, which breaks compilation.
- Added a test case to `esmToCommonJS.test.ts`
- Tested locally (replaced the problematic import statement in `bundle.js`)
=> Convert aliased imports to require statements

client/vscode-lib/src/util/importHelpers.ts
This way, if there is an error in require()ing the module, it's easier to see which provider the error came from.
=> use cjs-string:FILENAME instead of <CJS-STRING> for easier debuggability

provider/jira/README.md
Fixes https://linear.app/sourcegraph/issue/CODY-2245/jira-openctx-docs-incorrectly-reference-host-instead-of-url
=> Fix `email` param in Jira readme

lib/client/src/api.test.ts, lib/client/src/api.ts
This introduces a new option when calling an observable method on the client. It allows a caller to collect errors on the underlying providers.
Currently the client implementation when encountering an error in a provider will log it and then swallow it unbeknownst to the client. This is reasonable behaviour since we don't want one bad provider causing all of OpenCtx to fail. For example if the methods where to throw errors you wouldn't be able to collect the working provider results.
As an alternative I considered updating the return type of the client to either return the underlying type or an error. This ended up being quite a large change and didn't feel like it justified it for the extra burden it imposed on each call site. However, I can go that route so that each client explicitly …
=> client: add ObserveOptions.errorHook

client/vscode-lib/src/controller.ts, lib/client/src/index.ts
I accidently exported the name as an earlier name I had while working.
Test Plan: CI
=> client: remove alias for ProviderMethodOptions

web/pages/index/+Page.tsx
Fixes https://linear.app/sourcegraph/issue/CODY-2099/context-providers-link-on-openctxorg-homepage-is-broken
=> web: remove links to pages that don't exist

bin/package.json, client/vscode-lib/package.json, client/vscode-lib/src/controller.test.ts, client/vscode-lib/src/controller.ts, client/vscode-lib/src/util/cache.ts, client/vscode-lib/src/util/errorReporter.ts, client/vscode-lib/src/util/errorWaiter.ts, client/vscode/package.json, client/vscode/src/extension.ts, lib/client/package.json, lib/client/src/api.ts, lib/client/src/client/client.ts
This commit factors out the error reporting logic inside of createController into an errorReporter interface. ErrorReporter also provides functionality so we can use the errorHooks.
From my testing, it is useful to do error reporting per method. For example a misconfigured provider will trip the errorWaiter, leading to errors when calling mentions not being reported.
Test Plan: linked openctx into cody and tested with my usual providers, a missing provider and a provider which throws an error mentions. I observed on cody chat startup complaints about the missing provider and complaints again when the error provider is called for mentions.
https://github.com/sourcegraph/openctx/assets/187831/858fabde-dec6-4375-98b3-bd3f1db0b41f
=> vscode-lib: use errorHook to report errors

client/vscode-lib/package.json
Only way I could convince pnpm to create a dist dir.
=> vscode-lib: add prepublishOnly step

client/vscode-lib/package.json, client/vscode-lib/src/controller.ts, lib/client/package.json, lib/client/src/client/client.ts
This setting allows us to preload the openctx providers after a delay (which could be zero milliseconds). The intention is for Cody to set a reasonable value here (5s?) so that when a user does the first @ mention the providers have already been fetched.
Test Plan: added logging and observed the preload completing before activating the cody chat panel. Then loaded the cody chat panel and instantly do a mention. All OpenCtx providers where immediate.
Part of https://linear.app/sourcegraph/issue/CODY-1898/preload-openctx-providers-for-faster-user-typing
=> client: introduce preloadDelay

lib/protocol/package.json, lib/protocol/src/openctx-protocol.schema.json, lib/protocol/src/openctx-protocol.schema.ts, provider/azure-devops-workitems/index.ts, provider/azure-devops-workitems/package.json, provider/confluence/index.ts, provider/confluence/package.json, provider/devdocs/index.test.ts, provider/devdocs/index.ts, provider/devdocs/package.json, provider/github/package.json, provider/github/provider.ts, provider/google-docs/index.test.ts, provider/google-docs/index.ts, provider/google-docs/package.json, provider/jira/index.ts, provider/jira/package.json, provider/semgrep/index.test.ts, provider/semgrep/index.ts, provider/semgrep/package.json, provider/sentry/package.json, provider/sentry/provider.test.ts, provider/sentry/provider.ts, provider/slack/index.ts, provider/slack/package.json, provider/web/index.ts, provider/web/package.json
The intention behind this field is this is the placeholder label that is shown when a user selects a provider for mentioning, but before they have searched anything.
Part of https://linear.app/sourcegraph/issue/CODY-2275/add-all-the-right-labels-for-provider-mentions-query-stats
=> protocol: add meta.mentions.label

provider/devdocs/index.test.ts, provider/devdocs/index.ts
I noticed the other providers have this behaviour and it feels nice.
=> devdocs: return results for empty query

provider/linear-issues/index.ts, provider/linear-issues/package.json
This was a typo, previously we fetched assigned issues but accidently never read the field.
=> linear-issues: correctly include assigned issues

provider/linear-issues/index.ts
This makes the next change clearer which requires getAccessToken to be async.
=> provider: linear uses async await for getAccessToken

client/vscode-lib/package.json, client/vscode-lib/src/controller.ts, client/vscode-lib/src/global.ts, pnpm-lock.yaml, provider/linear-issues/index.ts, provider/linear-issues/package.json
Currently vscode doesn't support dynamic imports, so it isn't possible for a javascript provider to opt-in to more advanced user experience via the vscode APIs.
Until we can more easily opt-in to vscode support, we expose the vscode API via node's global object. We want to see what sort of APIs get used from vscode in providers, and will then likely evolve a first class editor abstraction.
=> vscode-lib: expose vscode API via global

client/vscode-lib/package.json
I fat fingered publishing 0.0.12 without first bundling the latest version of the code into dist.
=> vscode-lib: bump version to 0.0.13

.github/workflows/semgrep.yml
As similar to sourcegraph/sourcegraph and sourcegraph/cody repo we would like to enable Semgrep SAST for this repo. This check is non-blocking and optional check for now so, you can still merge without any issues.
This Github action should execute less than a minute (~30 sec to 1 minute at max). Semgrep helps to detect security vulnerabilities in code & bad pattern by scanning through the code changes.
Why does it matter?
CI 🟢
=> Adding Semgrep SAST Github Action

bin/package.json, client/vscode-lib/package.json, lib/client/package.json, lib/protocol/package.json, lib/protocol/src/openctx-protocol.schema.json, lib/protocol/src/openctx-protocol.schema.ts, lib/provider/package.json, provider/hello-world/index.test.ts, provider/hello-world/index.ts, provider/hello-world/package.json
Context: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1721935489008949
A customer wants to return context items from their provider if the user's query matches some keywords. They wish to bypass the whole mentions process and return context items for queries on submission time. 
This makes sense and is useful. 
This PR adds `meta.items.querySelectors` which will be used at query evaluation time to match with query and then call `provider.items` for the matching providers to collect context items.
=> Add query selector config

client/vscode-lib/src/controller.test.ts, client/vscode-lib/src/controller.ts, client/vscode-lib/src/util/errorReporter.ts, lib/client/src/api.ts, lib/client/src/client/client.test.ts, lib/client/src/client/client.ts, lib/client/src/client/testdata/simple.js, lib/client/src/client/testdata/simpleMeta.js, lib/client/src/client/util.test.ts, lib/client/src/client/util.ts
Previously, the client and controller only exposed a "watch" API using RxJS Observables so that callers could subscribe to and watch changes (to mentions, annotations, etc.). This required callers to depend on RxJS, which is a big dependency that can introduce complexity in their own applications. Now, there is a new API `xyzChanges__asyncGenerator` for each of `meta`, `mentions`, `items`, and `annotations` that lets callers just use native async generators. This API is experimental and may be changed without notice.
=> expose async-generator client API

client/vscode-lib/package.json, client/vscode-lib/src/controller.ts, lib/client/package.json, lib/client/src/api.ts, lib/client/src/client/client.test.ts, lib/client/src/client/client.ts, lib/client/src/client/util.test.ts, lib/client/src/client/util.ts, lib/client/src/index.ts
This lets that value change after initial client creation.
=> accept client providers via Observable/AsyncGenerator

provider/storybook/index.test.ts, provider/storybook/index.ts
The Storybook docs use `*.stories.[jt]s?(x)` as the filename format for stories modules. https://storybook.js.org/docs/writing-stories
=> provider/storybook: Allow *.stories.ts

lib/protocol/src/openctx-protocol.schema.json, lib/protocol/src/openctx-protocol.schema.ts, provider/hello-world/index.test.ts, provider/hello-world/index.ts, provider/hello-world/package.json, web/content/docs/protocol.mdx
Update the hello world example to auto-include mentions and consume active editor uri in example
=> Auto include hello world mentions

provider/github/README.md, provider/github/provider.ts
They are just example links so don't actually need to work, but got a report they no longer work. Update to most popular code repo on GitHub. 
Fixes https://github.com/sourcegraph/openctx/issues/203
=> github: update example links

client/browser/src/contentScript/contentScript.main.ts, client/browser/src/contentScript/github/codeView.ts, client/browser/src/contentScript/github/pullRequestFilesView.ts, client/vscode-lib/src/controller.ts, lib/client/src/api.test.ts, lib/client/src/api.ts, lib/client/src/client/client.ts, lib/client/src/misc/observable.test.ts, lib/client/src/misc/observable.ts
- use custom isEqualJSON instead of JSON.stringify (for which key order matters)
- use switchMap instead of mergeMap to stop unwanted emissions
=> improve observables usage

client/vscode-lib/src/controller.ts, client/vscode-lib/src/util/cache.ts, client/vscode-lib/src/util/errorReporter.ts
- OpenCtx no longer uses vscode.window.showErrorMessage, which is annoying and louder than most provider errors deserve.
- The output channel includes information about which provider the error came from, to make debugging easier.
=> quieter provider errors with better origin information

client/browser/README.md, client/browser/src/contentScript/github/codeView.ts, client/browser/src/contentScript/github/pullRequestFilesView.ts, web/content/docs/clients/github.mdx, web/content/docs/start.mdx, web/pages/docs/components/SourcegraphGettingStartedCommon.mdx
`sourcegraph/sourcegraph` went private, so links and references became invalid.
I noticed the stale links in https://openctx.org/docs/clients/sourcegraph first: the example files are all linked to `sourcegraph/sourcegraph`, pinned to a commit.
This is one of the examples: [SignInPage.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6cdadefe437e0c7a1afe28da424982ebe72b3654/-/blob/client/web/src/auth/SignInPage.tsx)
=> Update repositories to use sourcegraph/sourcegraph-public-snapshot

lib/client/src/providerClient/transport/createTransport.test.ts, lib/client/src/providerClient/transport/http.ts
The spec says that HTTP providers are invoked with a POST whose body includes the settings (https://openctx.org/docs/protocol). However, this was not happening; only the `params` were being sent. This fix makes it so that the `settings` are also passed.
=> pass settings in all HTTP provider invocations

provider/github/README.md
This change ensures consistent capitalization of the GitHub and GitLab brand names in Markdown documentation.
[_Created by Sourcegraph batch change `sqs/capitalize-brands-correctly`._](https://sourcegraph.sourcegraph.com/users/sqs/batch-changes/capitalize-brands-correctly)
=> Fix GitHub/GitLab brand capitalization

provider/github/provider.ts
This change ensures the GitHub brand name is capitalized correctly in the provider module.
=> fix: correct GitHub brand capitalization in provider

pnpm-lock.yaml, provider/sourcegraph-refs/README.md, provider/sourcegraph-refs/graphql.ts, provider/sourcegraph-refs/graphql_blobs.ts, provider/sourcegraph-refs/graphql_symbols.ts, provider/sourcegraph-refs/graphql_usages.ts, provider/sourcegraph-refs/index.ts, provider/sourcegraph-refs/package.json, provider/sourcegraph-refs/tsconfig.json, provider/sourcegraph-refs/vitest.config.ts
https://github.com/user-attachments/assets/bfd5867d-ab41-42fb-8434-c24e0da640cf
=> provider for usage examples from sourcegraph api

provider/modelcontextprotocol/README.md
this is necessary to connect multiple MCP servers and not have duplicate keys
=> add query params to mcp url examples
